package com.record.dao;

import com.record.model.User;

import java.util.List;

public interface UserDao {

    List<User> selectAllUser();

    List<User> selectUserByUserId(long id);

    User selectUserByUserName(String userName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated
     */
    int insertSelective(User record);

}